listen=YES
listen_port=2121
listen_ipv6=NO
anonymous_enable=NO
local_enable=YES
write_enable=YES

#sec chroot user in repo
chroot_local_user=YES
allow_writeable_chroot=YES

#expose Wp volume her
local_root=/home/${FTP_USER}/ftp

#usefull logs
xferlog_enable=YES
log_ftp_protocol=YES

#passif mode 
pasv_enable=YES
pasv_min_port=${PASV_MIN_PORT}
pasv_max_port=${PASV_MAX_PORT}
pasv_address=${PASV_ADDRESS}

#compatibility clients
seccomp_sandbox=NO